### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by yuritoledo** [naoufal/react-native-payments#166]
Hello,

I basically copied the tutorial code and added to my project, linked too ... and nothing happens :/

check out my data:

```
  const handleAndroidPayPress = () => {
    const paymentRequest = new PaymentRequest(METHOD_DATA, DETAILS)
    paymentRequest.show()
  }
{...}

const DETAILS = {
  id: 'basic-example',
  displayItems: [
    {
      label: 'Movie Ticket',
      amount: { currency: 'BRL', value: '1.00' }
    }
  ],
  total: {
    label: 'Merchant Name',
    amount: { currency: 'BRL', value: '1.00' }
  }
}


const METHOD_DATA = [{
  supportedMethods: ['android-pay'],
  data: {
    .
    supportedNetworks: ['visa', 'mastercard', 'amex'],
    currencyCode: 'BRL',
    environment: 'TEST', // defaults to production
    paymentMethodTokenizationParameters: {
      tokenizationType: 'NETWORK_TOKEN',
      parameters: {
        publicKey: 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIsFro6K+IUxRr4yFTOTO+kFCCEvHo7B9IOMLxah6c977oFzX/beObH4a9OfosMHmft3JJZ6B3xpjIb8kduK4/A=='
      }
    }
  }
}]

```

**Comment by Mlobaievskyi** [comment]
@yuritoledo replace `ios/ReactNativePayments.podspec` with 
```
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
version = package["version"]
giturl = package["repository"]

Pod::Spec.new do |s|
  s.name         = "ReactNativePayments"
  s.version      = package["version"]
  s.summary      = "react-native-payments"
  s.description  = <<-DESC
                  Native Payments (Google and Apple Pay) from React-Native
                   DESC
  s.homepage     = giturl
  s.license      = "MIT"
  s.authors      = "Naoufal Kadhom", "Andrej Badin"
  s.platform     = :ios, '10.0'
  s.source       = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
  s.source_files  = 'lib/ios/*.{h,m}'
  s.requires_arc = true

  s.dependency "React"

end
```
then again `pod install`  and `react-native link` or link manually https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by yuritoledo** [comment]
I am using Android! And the public I got in internet. I dont know how to get my own. Do you know?

**Comment by rathoreabhijeet** [comment]
Thanks @Mlobaievskyi . Your solution works, I wonder why this is missed in the package, when it SHOULD have a "React" dependency. 

If someone else is facing this, 
- I just edited my `node_modules/react-native-payments/ReactNativePayments.podspec` with the code given by @Mlobaievskyi . 
- Went to `iOS` folder and ran `pod install`. For this I had to lower the platform version in the above file to `9.0` as I was already building for minimum version 9.0, and `pod install` was giving error ( I figured I can either change this version, or start all over again with a higher deployment version)
- `react-native link react-native-payments` once again

... and it started working !

**Comment by rich-97** [comment]
I have the same issue with Android Pay.

**Comment by DougThwaites** [comment]
In case this helps anyone for me I am developing for iOS/ApplePay and am just selling a single product with one fixed shipping cost so I hadn't registered the 'shippingaddresschange' and 'shippingoptionschange' listeners once I did the promise got handled.

Since I just had the one shipping method I just updated the paymentRequest with the same details as it started with.

Also I had already done the podspec changes that @Mlobaievskyi pointed out and if you haven't already please do that also as that fixes alot of compiling errors.

**Comment by nikunjg** [comment]
is it fixed yet. how do we take care of changing files in node_modules folder in CI/CD.

**Comment by DougThwaites** [comment]
Hey @nikunjg if you are referring to the Podspec file for iOS I made a local copy of this package and then included the local version in my package.json and commit the local version of the package.

I know this isn't a perfect solution but its a solution :)

**Comment by nikunjg** [comment]
@DougThwaites, Can you please point me to sample project on github if there is any. It will be very useful for me. I am stuck with this long time.

**Comment by DougThwaites** [comment]
Hi @nikunjg I didn't upload a project to GitHub or fork the original repo but in short.

1. Copy react-native-payments directory from your node_modules directory
2. Paste it some else for instance I created a local_packages directory to put it in
3. I then modified the ios/ReactNativePayments.podspec file as per @Mlobaievskyi example
4. I installed my local version instead e.g. `yarn add file:local_packages/react-native-payments`
5. I committed my local package to my project in GitHub

_Note: This is not a good solution a fork of this repo or submitting a pull request would be better but it does the job._

I did this to get it to work in AppCenter for remote building so its the same thing for CI/CD as you mentioned.

**Comment by vdikun** [comment]
Thanks for raising this issue @yuritoledo . I am having this issue as well. I followed the instructions given by @Mlobaievskyi and @rathoreabhijeet. However after running `pod install` and `react-native link react-native-payments` I'm still getting the error: "Unhandled Promise Rejection". I understand that this indicates a linking error. So I attempt to manually link the library.

In Xcode, "ReactNativePayments.xcodeproj" is not present under Libraries.

Following the instructions at https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking, I go to look for  in myproj/node_modules/react-native/Libraries/, but there is no folder containing ReactNativePayments.xcodeproj.

At this point I do not know what else to do. How can I manually link this library?

**Comment by Knight704** [comment]
I'm faced with the same issue, and use solution to alter ```node_modules/react-native-payments/ReactNativePayments.podspec```
To be consistent on CI side too I used [patch-package](https://www.npmjs.com/package/patch-package) for this file

**Comment by dineshkokare123** [comment]
@Mlobaievskyi @rathoreabhijeet  
 can anyone help me to solve this issue  possible unhandled promise rejection type error undefined is not an object ('ReactNativePayments.canMakePayments')

const METHOD_DATA = [{
  supportedMethods: ['apple-pay'],
  data: {
    merchantIdentifier: 'merchant.com.arganpackage.arganpackage',
    supportedNetworks: ['visa', 'mastercard', 'amex'],
    countryCode: 'US',
    currencyCode: 'USD'
  }
}];

const DETAILS = {
  id: 'basic-example',
  displayItems: [
    {
      label: 'Movie Ticketre',
      amount: { currency: 'USD', value: '15.00' }
    },
    {
      label: 'Grocery',
      amount: { currency: 'USD', value: '5.00' }
    }
  ],
  shippingOptions: [{
    id: 'economy',
    label: 'Economy Shipping',
    amount: { currency: 'USD', value: '0.00' },
    detail: 'Arrives in 3-5 days' // `detail` is specific to React Native Payments
  }],
  total: {
    label: 'Enappd Store',
    amount: { currency: 'USD', value: '20.00' }
  }
};
const OPTIONS = {
  requestPayerName: true,
  requestPayerPhone: true,
  requestPayerEmail: true,
  requestShipping: true
};
const paymentRequest = new PaymentRequest(METHOD_DATA, DETAILS, OPTIONS);

paymentRequest.addEventListener('shippingaddresschange', e => {
  const updatedDetails = getUpdatedDetailsForShippingAddress(paymentRequest.shippingAddress);

  e.updateWith(updatedDetails);
});

paymentRequest.addEventListener('shippingoptionchange', e => {
  const updatedDetails = getUpdatedDetailsForShippingOption(paymentRequest.shippingOption);

  e.updateWith(updatedDetails);
});

check = () => {
  paymentRequest.canMakePayments().then((canMakePayment) => {
    if (canMakePayment) {
      Alert.alert(
        'Apple Pay',
        'Apple Pay is available in this device'
      );
    }
  })
}

pay = () => {
    paymentRequest.canMakePayments().then((canMakePayment) => {
    if (canMakePayment) {
      console.log('Can Make Payment')
      paymentRequest.show()
        .then(paymentResponse => {
          // Your payment processing code goes here

          paymentResponse.complete('success');
        });
    }
    else {
      console.log('Cant Make Payment')
    }
  })
}


ReactNativePayments.podspec file
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
version = package["version"]
giturl = package["repository"]

Pod::Spec.new do |s|
  s.name         = "ReactNativePayments"
  s.version      = package["version"]
  s.summary      = "react-native-payments"
  s.description  = <<-DESC
                  Native Payments (Google and Apple Pay) from React-Native
                   DESC
  s.homepage     = giturl
  s.license      = "MIT"
  s.authors      = "Naoufal Kadhom", "Andrej Badin"
  s.platform     = :ios, '10.0'
  s.source       = { :git => "https://github.com/naoufal/react-native-payments.git", :tag => "#{s.version}" }
  s.source_files  = 'packages/react-native-payments/lib/ios/*.{h,m}'
  s.requires_arc = true

  s.dependency "React"


end


after that, I have installed the pod file and link the react-native payment library still not solved the issue.

**Comment by nabilfreeman** [comment]
Hey @dineshkokare123 , it looks like you are on an older version of RNP, try out 0.8.0 and the example iOS project here https://github.com/freeman-industries/react-native-payments-example-ios

**Comment by nabilfreeman** [comment]
I'm going to close this issue team, we've just release 0.8.0 which has a fixed podspec and a working example project for RN 0.63 (linked above).

Please open a new issue if you problems persist and link us to a fork of the example project with your breaking code inside.

**Comment by dineshkokare123** [comment]
@nabilfreeman  thanks for your valuable response.
